/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Announcement model module.
 * @module model/Announcement
 * @version 1.0.0
 */
export class Announcement {
  /**
   * Constructs a new <code>Announcement</code>.
   * @alias module:model/Announcement
   * @class
   * @param id {String} 
   * @param category {String} 
   * @param priority {String} 
   * @param content {Object.<String, String>} 
   */
  constructor(id, category, priority, content) {
    this.id = id;
    this.category = category;
    this.priority = priority;
    this.content = content;
  }

  /**
   * Constructs a <code>Announcement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Announcement} obj Optional instance to populate.
   * @return {module:model/Announcement} The populated <code>Announcement</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Announcement();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('priority'))
        obj.priority = ApiClient.convertToType(data['priority'], 'String');
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
Announcement.prototype.created = undefined;

/**
 * @member {Date} modified
 */
Announcement.prototype.modified = undefined;

/**
 * @member {String} id
 */
Announcement.prototype.id = undefined;

/**
 * @member {String} category
 */
Announcement.prototype.category = undefined;

/**
 * @member {String} priority
 */
Announcement.prototype.priority = undefined;

/**
 * @member {Object.<String, String>} content
 */
Announcement.prototype.content = undefined;

