/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Badge} from './Badge';

/**
 * The Badges model module.
 * @module model/Badges
 * @version 1.0.0
 */
export class Badges {
  /**
   * Constructs a new <code>Badges</code>.
   * @alias module:model/Badges
   * @class
   * @param badges {Array.<module:model/Badge>} 
   */
  constructor(badges) {
    this.badges = badges;
  }

  /**
   * Constructs a <code>Badges</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Badges} obj Optional instance to populate.
   * @return {module:model/Badges} The populated <code>Badges</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Badges();
      if (data.hasOwnProperty('badges'))
        obj.badges = ApiClient.convertToType(data['badges'], [Badge]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Badge>} badges
 */
Badges.prototype.badges = undefined;

