/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Badge model module.
 * @module model/Badge
 * @version 1.0.0
 */
export class Badge {
  /**
   * Constructs a new <code>Badge</code>.
   * @alias module:model/Badge
   * @class
   * @param name {String} 
   * @param displayName {Object.<String, String>} 
   * @param description {Object.<String, String>} 
   */
  constructor(name, displayName, description) {
    this.name = name;
    this.displayName = displayName;
    this.description = description;
  }

  /**
   * Constructs a <code>Badge</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Badge} obj Optional instance to populate.
   * @return {module:model/Badge} The populated <code>Badge</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Badge();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], {'String': 'String'});
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Badge.prototype.name = undefined;

/**
 * @member {Object.<String, String>} displayName
 */
Badge.prototype.displayName = undefined;

/**
 * @member {Object.<String, String>} description
 */
Badge.prototype.description = undefined;

