/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CarpropertiesProperties model module.
 * @module model/CarpropertiesProperties
 * @version 1.0.0
 */
export class CarpropertiesProperties {
  /**
   * Constructs a new <code>CarpropertiesProperties</code>.
   * @alias module:model/CarpropertiesProperties
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CarpropertiesProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CarpropertiesProperties} obj Optional instance to populate.
   * @return {module:model/CarpropertiesProperties} The populated <code>CarpropertiesProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CarpropertiesProperties();
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ApiClient.convertToType(data['manufacturer'], 'String');
      if (data.hasOwnProperty('model'))
        obj.model = ApiClient.convertToType(data['model'], 'String');
      if (data.hasOwnProperty('fuelType'))
        obj.fuelType = ApiClient.convertToType(data['fuelType'], 'String');
      if (data.hasOwnProperty('constructionYear'))
        obj.constructionYear = ApiClient.convertToType(data['constructionYear'], 'Number');
      if (data.hasOwnProperty('VIN'))
        obj.VIN = ApiClient.convertToType(data['VIN'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} manufacturer
 */
CarpropertiesProperties.prototype.manufacturer = undefined;

/**
 * @member {String} model
 */
CarpropertiesProperties.prototype.model = undefined;

/**
 * Allowed values for the <code>fuelType</code> property.
 * @enum {String}
 * @readonly
 */
CarpropertiesProperties.FuelTypeEnum = {
  /**
   * value: "diesel"
   * @const
   */
  diesel: "diesel",

  /**
   * value: "gasoline"
   * @const
   */
  gasoline: "gasoline",

  /**
   * value: "biodiesel"
   * @const
   */
  biodiesel: "biodiesel",

  /**
   * value: "kerosene"
   * @const
   */
  kerosene: "kerosene",

  /**
   * value: "electric"
   * @const
   */
  electric: "electric",

  /**
   * value: "hybrid"
   * @const
   */
  hybrid: "hybrid",

  /**
   * value: "gas"
   * @const
   */
  gas: "gas"
};
/**
 * @member {module:model/CarpropertiesProperties.FuelTypeEnum} fuelType
 */
CarpropertiesProperties.prototype.fuelType = undefined;

/**
 * @member {Number} constructionYear
 */
CarpropertiesProperties.prototype.constructionYear = undefined;

/**
 * @member {String} VIN
 */
CarpropertiesProperties.prototype.VIN = undefined;

