/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Exception1} from './Exception1';

/**
 * The CircularReference model module.
 * @module model/CircularReference
 * @version 1.0.0
 */
export class CircularReference {
  /**
   * Constructs a new <code>CircularReference</code>.
   * @alias module:model/CircularReference
   * @class
   * @param circularReference {module:model/Exception1} 
   */
  constructor(circularReference) {
    this.circularReference = circularReference;
  }

  /**
   * Constructs a <code>CircularReference</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CircularReference} obj Optional instance to populate.
   * @return {module:model/CircularReference} The populated <code>CircularReference</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CircularReference();
      if (data.hasOwnProperty('circularReference'))
        obj.circularReference = Exception1.constructFromObject(data['circularReference']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Exception1} circularReference
 */
CircularReference.prototype.circularReference = undefined;

// Implement MaybeCircularException interface:
