/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Components model module.
 * @module model/Components
 * @version 1.0.0
 */
export class Components {
  /**
   * Constructs a new <code>Components</code>.
   * @alias module:model/Components
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Components</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Components} obj Optional instance to populate.
   * @return {module:model/Components} The populated <code>Components</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Components();
      if (data.hasOwnProperty('schemas'))
        obj.schemas = ApiClient.convertToType(data['schemas'], Object);
      if (data.hasOwnProperty('responses'))
        obj.responses = ApiClient.convertToType(data['responses'], Object);
      if (data.hasOwnProperty('parameters'))
        obj.parameters = ApiClient.convertToType(data['parameters'], Object);
      if (data.hasOwnProperty('examples'))
        obj.examples = ApiClient.convertToType(data['examples'], Object);
      if (data.hasOwnProperty('requestBodies'))
        obj.requestBodies = ApiClient.convertToType(data['requestBodies'], Object);
      if (data.hasOwnProperty('headers'))
        obj.headers = ApiClient.convertToType(data['headers'], Object);
      if (data.hasOwnProperty('securitySchemes'))
        obj.securitySchemes = ApiClient.convertToType(data['securitySchemes'], Object);
      if (data.hasOwnProperty('links'))
        obj.links = ApiClient.convertToType(data['links'], Object);
      if (data.hasOwnProperty('callbacks'))
        obj.callbacks = ApiClient.convertToType(data['callbacks'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} schemas
 */
Components.prototype.schemas = undefined;

/**
 * @member {Object} responses
 */
Components.prototype.responses = undefined;

/**
 * @member {Object} parameters
 */
Components.prototype.parameters = undefined;

/**
 * @member {Object} examples
 */
Components.prototype.examples = undefined;

/**
 * @member {Object} requestBodies
 */
Components.prototype.requestBodies = undefined;

/**
 * @member {Object} headers
 */
Components.prototype.headers = undefined;

/**
 * @member {Object} securitySchemes
 */
Components.prototype.securitySchemes = undefined;

/**
 * @member {Object} links
 */
Components.prototype.links = undefined;

/**
 * @member {Object} callbacks
 */
Components.prototype.callbacks = undefined;

