/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Discriminator model module.
 * @module model/Discriminator
 * @version 1.0.0
 */
export class Discriminator {
  /**
   * Constructs a new <code>Discriminator</code>.
   * @alias module:model/Discriminator
   * @class
   * @param propertyName {String} 
   */
  constructor(propertyName) {
    this.propertyName = propertyName;
  }

  /**
   * Constructs a <code>Discriminator</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Discriminator} obj Optional instance to populate.
   * @return {module:model/Discriminator} The populated <code>Discriminator</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Discriminator();
      if (data.hasOwnProperty('propertyName'))
        obj.propertyName = ApiClient.convertToType(data['propertyName'], 'String');
      if (data.hasOwnProperty('mapping'))
        obj.mapping = ApiClient.convertToType(data['mapping'], {'String': 'String'});
    }
    return obj;
  }
}

/**
 * @member {String} propertyName
 */
Discriminator.prototype.propertyName = undefined;

/**
 * @member {Object.<String, String>} mapping
 */
Discriminator.prototype.mapping = undefined;

