/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Exception1} from './Exception1';

/**
 * The Exception model module.
 * @module model/Exception
 * @version 1.0.0
 */
export class Exception {
  /**
   * Constructs a new <code>Exception</code>.
   * @alias module:model/Exception
   * @class
   * @param statusCode {Number} 
   * @param reasonPhrase {String} 
   */
  constructor(statusCode, reasonPhrase) {
    this.statusCode = statusCode;
    this.reasonPhrase = reasonPhrase;
  }

  /**
   * Constructs a <code>Exception</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Exception} obj Optional instance to populate.
   * @return {module:model/Exception} The populated <code>Exception</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Exception();
      if (data.hasOwnProperty('statusCode'))
        obj.statusCode = ApiClient.convertToType(data['statusCode'], 'Number');
      if (data.hasOwnProperty('reasonPhrase'))
        obj.reasonPhrase = ApiClient.convertToType(data['reasonPhrase'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], Object);
      if (data.hasOwnProperty('stackTrace'))
        obj.stackTrace = Exception1.constructFromObject(data['stackTrace']);
    }
    return obj;
  }
}

/**
 * @member {Number} statusCode
 */
Exception.prototype.statusCode = undefined;

/**
 * @member {String} reasonPhrase
 */
Exception.prototype.reasonPhrase = undefined;

/**
 * @member {String} message
 */
Exception.prototype.message = undefined;

/**
 * @member {Object} details
 */
Exception.prototype.details = undefined;

/**
 * @member {module:model/Exception1} stackTrace
 */
Exception.prototype.stackTrace = undefined;

