/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ExternalDocumentation model module.
 * @module model/ExternalDocumentation
 * @version 1.0.0
 */
export class ExternalDocumentation {
  /**
   * Constructs a new <code>ExternalDocumentation</code>.
   * @alias module:model/ExternalDocumentation
   * @class
   * @param url {String} 
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>ExternalDocumentation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalDocumentation} obj Optional instance to populate.
   * @return {module:model/ExternalDocumentation} The populated <code>ExternalDocumentation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExternalDocumentation();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
ExternalDocumentation.prototype.description = undefined;

/**
 * @member {String} url
 */
ExternalDocumentation.prototype.url = undefined;

