/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Fueling} from './Fueling';

/**
 * The Fuelings model module.
 * @module model/Fuelings
 * @version 1.0.0
 */
export class Fuelings {
  /**
   * Constructs a new <code>Fuelings</code>.
   * @alias module:model/Fuelings
   * @class
   * @param fuelings {Array.<module:model/Fueling>} 
   */
  constructor(fuelings) {
    this.fuelings = fuelings;
  }

  /**
   * Constructs a <code>Fuelings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fuelings} obj Optional instance to populate.
   * @return {module:model/Fuelings} The populated <code>Fuelings</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fuelings();
      if (data.hasOwnProperty('fuelings'))
        obj.fuelings = ApiClient.convertToType(data['fuelings'], [Fueling]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Fueling>} fuelings
 */
Fuelings.prototype.fuelings = undefined;

