/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NumberWithUnit} from './NumberWithUnit';
import {Sensor} from './Sensor';
import {User} from './User';

/**
 * The Fueling model module.
 * @module model/Fueling
 * @version 1.0.0
 */
export class Fueling {
  /**
   * Constructs a new <code>Fueling</code>.
   * @alias module:model/Fueling
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Fueling</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fueling} obj Optional instance to populate.
   * @return {module:model/Fueling} The populated <code>Fueling</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fueling();
      if (data.hasOwnProperty('fuelType'))
        obj.fuelType = ApiClient.convertToType(data['fuelType'], 'String');
      if (data.hasOwnProperty('comment'))
        obj.comment = ApiClient.convertToType(data['comment'], 'String');
      if (data.hasOwnProperty('car'))
        obj.car = Sensor.constructFromObject(data['car']);
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('cost'))
        obj.cost = NumberWithUnit.constructFromObject(data['cost']);
      if (data.hasOwnProperty('mileage'))
        obj.mileage = NumberWithUnit.constructFromObject(data['mileage']);
      if (data.hasOwnProperty('volume'))
        obj.volume = NumberWithUnit.constructFromObject(data['volume']);
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('missedFuelStop'))
        obj.missedFuelStop = ApiClient.convertToType(data['missedFuelStop'], 'Boolean');
      if (data.hasOwnProperty('partialFueling'))
        obj.partialFueling = ApiClient.convertToType(data['partialFueling'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} fuelType
 */
Fueling.prototype.fuelType = undefined;

/**
 * @member {String} comment
 */
Fueling.prototype.comment = undefined;

/**
 * @member {module:model/Sensor} car
 */
Fueling.prototype.car = undefined;

/**
 * @member {module:model/User} user
 */
Fueling.prototype.user = undefined;

/**
 * @member {module:model/NumberWithUnit} cost
 */
Fueling.prototype.cost = undefined;

/**
 * @member {module:model/NumberWithUnit} mileage
 */
Fueling.prototype.mileage = undefined;

/**
 * @member {module:model/NumberWithUnit} volume
 */
Fueling.prototype.volume = undefined;

/**
 * @member {Date} time
 */
Fueling.prototype.time = undefined;

/**
 * @member {Date} created
 */
Fueling.prototype.created = undefined;

/**
 * @member {Date} modified
 */
Fueling.prototype.modified = undefined;

/**
 * @member {String} id
 */
Fueling.prototype.id = undefined;

/**
 * @member {Boolean} missedFuelStop
 */
Fueling.prototype.missedFuelStop = undefined;

/**
 * @member {Boolean} partialFueling
 */
Fueling.prototype.partialFueling = undefined;

