/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Group} from './Group';

/**
 * The GroupActivity model module.
 * @module model/GroupActivity
 * @version 1.0.0
 */
export class GroupActivity {
  /**
   * Constructs a new <code>GroupActivity</code>.
   * @alias module:model/GroupActivity
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GroupActivity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupActivity} obj Optional instance to populate.
   * @return {module:model/GroupActivity} The populated <code>GroupActivity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupActivity();
      if (data.hasOwnProperty('group'))
        obj.group = Group.constructFromObject(data['group']);
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Group} group
 */
GroupActivity.prototype.group = undefined;

/**
 * @member {String} type
 */
GroupActivity.prototype.type = undefined;

// Implement OneOfactivity interface:
