/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GroupModify model module.
 * @module model/GroupModify
 * @version 1.0.0
 */
export class GroupModify {
  /**
   * Constructs a new <code>GroupModify</code>.
   * @alias module:model/GroupModify
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GroupModify</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupModify} obj Optional instance to populate.
   * @return {module:model/GroupModify} The populated <code>GroupModify</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupModify();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
GroupModify.prototype.description = undefined;

