/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Group} from './Group';

/**
 * The Groups model module.
 * @module model/Groups
 * @version 1.0.0
 */
export class Groups {
  /**
   * Constructs a new <code>Groups</code>.
   * @alias module:model/Groups
   * @class
   * @param groups {Array.<module:model/Group>} 
   */
  constructor(groups) {
    this.groups = groups;
  }

  /**
   * Constructs a <code>Groups</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Groups} obj Optional instance to populate.
   * @return {module:model/Groups} The populated <code>Groups</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Groups();
      if (data.hasOwnProperty('groups'))
        obj.groups = ApiClient.convertToType(data['groups'], [Group]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Group>} groups
 */
Groups.prototype.groups = undefined;

