/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The GroupCreate model module.
 * @module model/GroupCreate
 * @version 1.0.0
 */
export class GroupCreate {
  /**
   * Constructs a new <code>GroupCreate</code>.
   * @alias module:model/GroupCreate
   * @class
   * @param name {String} 
   * @param description {String} 
   */
  constructor(name, description) {
    this.name = name;
    this.description = description;
  }

  /**
   * Constructs a <code>GroupCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GroupCreate} obj Optional instance to populate.
   * @return {module:model/GroupCreate} The populated <code>GroupCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GroupCreate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
GroupCreate.prototype.name = undefined;

/**
 * @member {String} description
 */
GroupCreate.prototype.description = undefined;

