/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Contact} from './Contact';
import {License} from './License';

/**
 * The Info model module.
 * @module model/Info
 * @version 1.0.0
 */
export class Info {
  /**
   * Constructs a new <code>Info</code>.
   * @alias module:model/Info
   * @class
   * @param title {String} 
   * @param version {String} 
   */
  constructor(title, version) {
    this.title = title;
    this.version = version;
  }

  /**
   * Constructs a <code>Info</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Info} obj Optional instance to populate.
   * @return {module:model/Info} The populated <code>Info</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Info();
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('termsOfService'))
        obj.termsOfService = ApiClient.convertToType(data['termsOfService'], 'String');
      if (data.hasOwnProperty('contact'))
        obj.contact = Contact.constructFromObject(data['contact']);
      if (data.hasOwnProperty('license'))
        obj.license = License.constructFromObject(data['license']);
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} title
 */
Info.prototype.title = undefined;

/**
 * @member {String} description
 */
Info.prototype.description = undefined;

/**
 * @member {String} termsOfService
 */
Info.prototype.termsOfService = undefined;

/**
 * @member {module:model/Contact} contact
 */
Info.prototype.contact = undefined;

/**
 * @member {module:model/License} license
 */
Info.prototype.license = undefined;

/**
 * @member {String} version
 */
Info.prototype.version = undefined;

