/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Geometry} from './Geometry';
import {MeasurementcreateProperties} from './MeasurementcreateProperties';

/**
 * The MeasurementCreate model module.
 * @module model/MeasurementCreate
 * @version 1.0.0
 */
export class MeasurementCreate {
  /**
   * Constructs a new <code>MeasurementCreate</code>.
   * @alias module:model/MeasurementCreate
   * @class
   * @param type {module:model/MeasurementCreate.TypeEnum} 
   * @param geometry {module:model/Geometry} 
   * @param properties {module:model/MeasurementcreateProperties} 
   */
  constructor(type, geometry, properties) {
    this.type = type;
    this.geometry = geometry;
    this.properties = properties;
  }

  /**
   * Constructs a <code>MeasurementCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MeasurementCreate} obj Optional instance to populate.
   * @return {module:model/MeasurementCreate} The populated <code>MeasurementCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MeasurementCreate();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('geometry'))
        obj.geometry = Geometry.constructFromObject(data['geometry']);
      if (data.hasOwnProperty('properties'))
        obj.properties = MeasurementcreateProperties.constructFromObject(data['properties']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
MeasurementCreate.TypeEnum = {
  /**
   * value: "Feature"
   * @const
   */
  feature: "Feature"
};
/**
 * @member {module:model/MeasurementCreate.TypeEnum} type
 */
MeasurementCreate.prototype.type = undefined;

/**
 * @member {module:model/Geometry} geometry
 */
MeasurementCreate.prototype.geometry = undefined;

/**
 * @member {module:model/MeasurementcreateProperties} properties
 */
MeasurementCreate.prototype.properties = undefined;

