/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MeasurementcreatePropertiesPhenomenons model module.
 * @module model/MeasurementcreatePropertiesPhenomenons
 * @version 1.0.0
 */
export class MeasurementcreatePropertiesPhenomenons {
  /**
   * Constructs a new <code>MeasurementcreatePropertiesPhenomenons</code>.
   * @alias module:model/MeasurementcreatePropertiesPhenomenons
   * @class
   * @param value {Object} 
   */
  constructor(value) {
    this.value = value;
  }

  /**
   * Constructs a <code>MeasurementcreatePropertiesPhenomenons</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MeasurementcreatePropertiesPhenomenons} obj Optional instance to populate.
   * @return {module:model/MeasurementcreatePropertiesPhenomenons} The populated <code>MeasurementcreatePropertiesPhenomenons</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MeasurementcreatePropertiesPhenomenons();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} value
 */
MeasurementcreatePropertiesPhenomenons.prototype.value = undefined;

