/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Multipolygon model module.
 * @module model/Multipolygon
 * @version 1.0.0
 */
export class Multipolygon {
  /**
   * Constructs a new <code>Multipolygon</code>.
   * @alias module:model/Multipolygon
   * @class
   * @param type {Object} 
   * @param coordinates {Array.<Array.<Array.<Array.<Number>>>>} 
   */
  constructor(type, coordinates) {
    this.type = type;
    this.coordinates = coordinates;
  }

  /**
   * Constructs a <code>Multipolygon</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Multipolygon} obj Optional instance to populate.
   * @return {module:model/Multipolygon} The populated <code>Multipolygon</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Multipolygon();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], Object);
      if (data.hasOwnProperty('coordinates'))
        obj.coordinates = ApiClient.convertToType(data['coordinates'], [[[['Number']]]]);
    }
    return obj;
  }
}

/**
 * @member {Object} type
 */
Multipolygon.prototype.type = undefined;

/**
 * @member {Array.<Array.<Array.<Array.<Number>>>>} coordinates
 */
Multipolygon.prototype.coordinates = undefined;

// Implement Geometry interface:
