/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NumberWithUnit model module.
 * @module model/NumberWithUnit
 * @version 1.0.0
 */
export class NumberWithUnit {
  /**
   * Constructs a new <code>NumberWithUnit</code>.
   * @alias module:model/NumberWithUnit
   * @class
   * @param value {Number} 
   * @param unit {String} 
   */
  constructor(value, unit) {
    this.value = value;
    this.unit = unit;
  }

  /**
   * Constructs a <code>NumberWithUnit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NumberWithUnit} obj Optional instance to populate.
   * @return {module:model/NumberWithUnit} The populated <code>NumberWithUnit</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NumberWithUnit();
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} value
 */
NumberWithUnit.prototype.value = undefined;

/**
 * @member {String} unit
 */
NumberWithUnit.prototype.unit = undefined;

