/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Phenomenon model module.
 * @module model/Phenomenon
 * @version 1.0.0
 */
export class Phenomenon {
  /**
   * Constructs a new <code>Phenomenon</code>.
   * @alias module:model/Phenomenon
   * @class
   * @param name {String} 
   * @param unit {String} 
   */
  constructor(name, unit) {
    this.name = name;
    this.unit = unit;
  }

  /**
   * Constructs a <code>Phenomenon</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Phenomenon} obj Optional instance to populate.
   * @return {module:model/Phenomenon} The populated <code>Phenomenon</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Phenomenon();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Phenomenon.prototype.name = undefined;

/**
 * @member {String} unit
 */
Phenomenon.prototype.unit = undefined;

/**
 * @member {Date} created
 */
Phenomenon.prototype.created = undefined;

/**
 * @member {Date} modified
 */
Phenomenon.prototype.modified = undefined;

