/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PhenomenonCreate model module.
 * @module model/PhenomenonCreate
 * @version 1.0.0
 */
export class PhenomenonCreate {
  /**
   * Constructs a new <code>PhenomenonCreate</code>.
   * @alias module:model/PhenomenonCreate
   * @class
   * @param name {String} 
   * @param unit {String} 
   */
  constructor(name, unit) {
    this.name = name;
    this.unit = unit;
  }

  /**
   * Constructs a <code>PhenomenonCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhenomenonCreate} obj Optional instance to populate.
   * @return {module:model/PhenomenonCreate} The populated <code>PhenomenonCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PhenomenonCreate();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('unit'))
        obj.unit = ApiClient.convertToType(data['unit'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PhenomenonCreate.prototype.name = undefined;

/**
 * @member {String} unit
 */
PhenomenonCreate.prototype.unit = undefined;

