/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Phenomenon} from './Phenomenon';

/**
 * The Phenomenons model module.
 * @module model/Phenomenons
 * @version 1.0.0
 */
export class Phenomenons {
  /**
   * Constructs a new <code>Phenomenons</code>.
   * @alias module:model/Phenomenons
   * @class
   * @param phenomenons {Array.<module:model/Phenomenon>} 
   */
  constructor(phenomenons) {
    this.phenomenons = phenomenons;
  }

  /**
   * Constructs a <code>Phenomenons</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Phenomenons} obj Optional instance to populate.
   * @return {module:model/Phenomenons} The populated <code>Phenomenons</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Phenomenons();
      if (data.hasOwnProperty('phenomenons'))
        obj.phenomenons = ApiClient.convertToType(data['phenomenons'], [Phenomenon]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Phenomenon>} phenomenons
 */
Phenomenons.prototype.phenomenons = undefined;

