/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {PrivacystatementsPrivacyStatements} from './PrivacystatementsPrivacyStatements';

/**
 * The PrivacyStatements model module.
 * @module model/PrivacyStatements
 * @version 1.0.0
 */
export class PrivacyStatements {
  /**
   * Constructs a new <code>PrivacyStatements</code>.
   * @alias module:model/PrivacyStatements
   * @class
   * @param privacyStatements {Array.<module:model/PrivacystatementsPrivacyStatements>} 
   */
  constructor(privacyStatements) {
    this.privacyStatements = privacyStatements;
  }

  /**
   * Constructs a <code>PrivacyStatements</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrivacyStatements} obj Optional instance to populate.
   * @return {module:model/PrivacyStatements} The populated <code>PrivacyStatements</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrivacyStatements();
      if (data.hasOwnProperty('privacyStatements'))
        obj.privacyStatements = ApiClient.convertToType(data['privacyStatements'], [PrivacystatementsPrivacyStatements]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/PrivacystatementsPrivacyStatements>} privacyStatements
 */
PrivacyStatements.prototype.privacyStatements = undefined;

