/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PrivacyStatement model module.
 * @module model/PrivacyStatement
 * @version 1.0.0
 */
export class PrivacyStatement {
  /**
   * Constructs a new <code>PrivacyStatement</code>.
   * @alias module:model/PrivacyStatement
   * @class
   * @param id {String} 
   * @param issuedDate {Date} 
   * @param contents {String} 
   */
  constructor(id, issuedDate, contents) {
    this.id = id;
    this.issuedDate = issuedDate;
    this.contents = contents;
  }

  /**
   * Constructs a <code>PrivacyStatement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PrivacyStatement} obj Optional instance to populate.
   * @return {module:model/PrivacyStatement} The populated <code>PrivacyStatement</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PrivacyStatement();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('issuedDate'))
        obj.issuedDate = ApiClient.convertToType(data['issuedDate'], 'Date');
      if (data.hasOwnProperty('contents'))
        obj.contents = ApiClient.convertToType(data['contents'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
PrivacyStatement.prototype.created = undefined;

/**
 * @member {Date} modified
 */
PrivacyStatement.prototype.modified = undefined;

/**
 * @member {String} id
 */
PrivacyStatement.prototype.id = undefined;

/**
 * @member {Date} issuedDate
 */
PrivacyStatement.prototype.issuedDate = undefined;

/**
 * @member {String} contents
 */
PrivacyStatement.prototype.contents = undefined;

