/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Schemas model module.
 * @module model/Schemas
 * @version 1.0.0
 */
export class Schemas {
  /**
   * Constructs a new <code>Schemas</code>.
   * @alias module:model/Schemas
   * @class
   * @param schemas {Array.<String>} 
   */
  constructor(schemas) {
    this.schemas = schemas;
  }

  /**
   * Constructs a <code>Schemas</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Schemas} obj Optional instance to populate.
   * @return {module:model/Schemas} The populated <code>Schemas</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Schemas();
      if (data.hasOwnProperty('schemas'))
        obj.schemas = ApiClient.convertToType(data['schemas'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} schemas
 */
Schemas.prototype.schemas = undefined;

