/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SelfActivity model module.
 * @module model/SelfActivity
 * @version 1.0.0
 */
export class SelfActivity {
  /**
   * Constructs a new <code>SelfActivity</code>.
   * @alias module:model/SelfActivity
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SelfActivity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SelfActivity} obj Optional instance to populate.
   * @return {module:model/SelfActivity} The populated <code>SelfActivity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SelfActivity();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} type
 */
SelfActivity.prototype.type = undefined;

// Implement OneOfactivity interface:
