/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Sensor} from './Sensor';

/**
 * The Sensors model module.
 * @module model/Sensors
 * @version 1.0.0
 */
export class Sensors {
  /**
   * Constructs a new <code>Sensors</code>.
   * @alias module:model/Sensors
   * @class
   * @param sensors {Array.<module:model/Sensor>} 
   */
  constructor(sensors) {
    this.sensors = sensors;
  }

  /**
   * Constructs a <code>Sensors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Sensors} obj Optional instance to populate.
   * @return {module:model/Sensors} The populated <code>Sensors</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Sensors();
      if (data.hasOwnProperty('sensors'))
        obj.sensors = ApiClient.convertToType(data['sensors'], [Sensor]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Sensor>} sensors
 */
Sensors.prototype.sensors = undefined;

