/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SensorProperties model module.
 * @module model/SensorProperties
 * @version 1.0.0
 */
export class SensorProperties {
  /**
   * Constructs a new <code>SensorProperties</code>.
   * @alias module:model/SensorProperties
   * @class
   * @param id {String} 
   */
  constructor(id) {
    this.id = id;
  }

  /**
   * Constructs a <code>SensorProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SensorProperties} obj Optional instance to populate.
   * @return {module:model/SensorProperties} The populated <code>SensorProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SensorProperties();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
SensorProperties.prototype.id = undefined;

