/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ServerVariable model module.
 * @module model/ServerVariable
 * @version 1.0.0
 */
export class ServerVariable {
  /**
   * Constructs a new <code>ServerVariable</code>.
   * @alias module:model/ServerVariable
   * @class
   * @param _default {String} 
   */
  constructor(_default) {
    this._default = _default;
  }

  /**
   * Constructs a <code>ServerVariable</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ServerVariable} obj Optional instance to populate.
   * @return {module:model/ServerVariable} The populated <code>ServerVariable</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ServerVariable();
      if (data.hasOwnProperty('enum'))
        obj._enum = ApiClient.convertToType(data['enum'], ['String']);
      if (data.hasOwnProperty('default'))
        obj._default = ApiClient.convertToType(data['default'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} _enum
 */
ServerVariable.prototype._enum = undefined;

/**
 * @member {String} _default
 */
ServerVariable.prototype._default = undefined;

/**
 * @member {String} description
 */
ServerVariable.prototype.description = undefined;

