/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ServerVariable} from './ServerVariable';

/**
 * The Server model module.
 * @module model/Server
 * @version 1.0.0
 */
export class Server {
  /**
   * Constructs a new <code>Server</code>.
   * @alias module:model/Server
   * @class
   * @param url {String} 
   */
  constructor(url) {
    this.url = url;
  }

  /**
   * Constructs a <code>Server</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Server} obj Optional instance to populate.
   * @return {module:model/Server} The populated <code>Server</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Server();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('variables'))
        obj.variables = ApiClient.convertToType(data['variables'], {'String': ServerVariable});
    }
    return obj;
  }
}

/**
 * @member {String} url
 */
Server.prototype.url = undefined;

/**
 * @member {String} description
 */
Server.prototype.description = undefined;

/**
 * @member {Object.<String, module:model/ServerVariable>} variables
 */
Server.prototype.variables = undefined;

