/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Statistic} from './Statistic';

/**
 * The Statistics model module.
 * @module model/Statistics
 * @version 1.0.0
 */
export class Statistics {
  /**
   * Constructs a new <code>Statistics</code>.
   * @alias module:model/Statistics
   * @class
   * @param statistics {Array.<module:model/Statistic>} 
   */
  constructor(statistics) {
    this.statistics = statistics;
  }

  /**
   * Constructs a <code>Statistics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Statistics} obj Optional instance to populate.
   * @return {module:model/Statistics} The populated <code>Statistics</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Statistics();
      if (data.hasOwnProperty('statistics'))
        obj.statistics = ApiClient.convertToType(data['statistics'], [Statistic]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Statistic>} statistics
 */
Statistics.prototype.statistics = undefined;

