/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Sensor} from './Sensor';
import {TrackStatus} from './TrackStatus';
import {User} from './User';

/**
 * The TrackProperties model module.
 * @module model/TrackProperties
 * @version 1.0.0
 */
export class TrackProperties {
  /**
   * Constructs a new <code>TrackProperties</code>.
   * @alias module:model/TrackProperties
   * @class
   * @param id {String} 
   * @param sensor {module:model/Sensor} 
   */
  constructor(id, sensor) {
    this.id = id;
    this.sensor = sensor;
  }

  /**
   * Constructs a <code>TrackProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackProperties} obj Optional instance to populate.
   * @return {module:model/TrackProperties} The populated <code>TrackProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackProperties();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('sensor'))
        obj.sensor = Sensor.constructFromObject(data['sensor']);
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('appVersion'))
        obj.appVersion = ApiClient.convertToType(data['appVersion'], 'String');
      if (data.hasOwnProperty('obdDevice'))
        obj.obdDevice = ApiClient.convertToType(data['obdDevice'], 'String');
      if (data.hasOwnProperty('touVersion'))
        obj.touVersion = ApiClient.convertToType(data['touVersion'], 'Date');
      if (data.hasOwnProperty('length'))
        obj.length = ApiClient.convertToType(data['length'], 'Number');
      if (data.hasOwnProperty('begin'))
        obj.begin = ApiClient.convertToType(data['begin'], 'Date');
      if (data.hasOwnProperty('end'))
        obj.end = ApiClient.convertToType(data['end'], 'Date');
      if (data.hasOwnProperty('measurementProfile'))
        obj.measurementProfile = ApiClient.convertToType(data['measurementProfile'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = TrackStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
TrackProperties.prototype.id = undefined;

/**
 * @member {Date} created
 */
TrackProperties.prototype.created = undefined;

/**
 * @member {Date} modified
 */
TrackProperties.prototype.modified = undefined;

/**
 * @member {module:model/Sensor} sensor
 */
TrackProperties.prototype.sensor = undefined;

/**
 * @member {module:model/User} user
 */
TrackProperties.prototype.user = undefined;

/**
 * @member {String} name
 */
TrackProperties.prototype.name = undefined;

/**
 * @member {String} description
 */
TrackProperties.prototype.description = undefined;

/**
 * @member {String} appVersion
 */
TrackProperties.prototype.appVersion = undefined;

/**
 * @member {String} obdDevice
 */
TrackProperties.prototype.obdDevice = undefined;

/**
 * @member {Date} touVersion
 */
TrackProperties.prototype.touVersion = undefined;

/**
 * @member {Number} length
 */
TrackProperties.prototype.length = undefined;

/**
 * @member {Date} begin
 */
TrackProperties.prototype.begin = undefined;

/**
 * @member {Date} end
 */
TrackProperties.prototype.end = undefined;

/**
 * @member {String} measurementProfile
 */
TrackProperties.prototype.measurementProfile = undefined;

/**
 * @member {module:model/TrackStatus} status
 */
TrackProperties.prototype.status = undefined;

