/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Measurement} from './Measurement';
import {TrackProperties} from './TrackProperties';

/**
 * The Track model module.
 * @module model/Track
 * @version 1.0.0
 */
export class Track {
  /**
   * Constructs a new <code>Track</code>.
   * @alias module:model/Track
   * @class
   * @param type {module:model/Track.TypeEnum} 
   * @param features {Array.<module:model/Measurement>} 
   * @param properties {module:model/TrackProperties} 
   */
  constructor(type, features, properties) {
    this.type = type;
    this.features = features;
    this.properties = properties;
  }

  /**
   * Constructs a <code>Track</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Track} obj Optional instance to populate.
   * @return {module:model/Track} The populated <code>Track</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Track();
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('features'))
        obj.features = ApiClient.convertToType(data['features'], [Measurement]);
      if (data.hasOwnProperty('properties'))
        obj.properties = TrackProperties.constructFromObject(data['properties']);
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
Track.TypeEnum = {
  /**
   * value: "FeatureCollection"
   * @const
   */
  featureCollection: "FeatureCollection"
};
/**
 * @member {module:model/Track.TypeEnum} type
 */
Track.prototype.type = undefined;

/**
 * @member {Array.<module:model/Measurement>} features
 */
Track.prototype.features = undefined;

/**
 * @member {module:model/TrackProperties} properties
 */
Track.prototype.properties = undefined;

