/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class TrackStatus.
 * @enum {String}
 * @readonly
 */
const TrackStatus = {
  /**
   * value: "finished"
   * @const
   */
  finished: "finished",

  /**
   * value: "ongoing"
   * @const
   */
  ongoing: "ongoing",

  /**
   * Returns a <code>TrackStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TrackStatus} The enum <code>TrackStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {TrackStatus};