/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TrackStatus} from './TrackStatus';

/**
 * The TrackcreateProperties model module.
 * @module model/TrackcreateProperties
 * @version 1.0.0
 */
export class TrackcreateProperties {
  /**
   * Constructs a new <code>TrackcreateProperties</code>.
   * @alias module:model/TrackcreateProperties
   * @class
   * @param sensor {String} the name of an existing sensor resource
   */
  constructor(sensor) {
    this.sensor = sensor;
  }

  /**
   * Constructs a <code>TrackcreateProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackcreateProperties} obj Optional instance to populate.
   * @return {module:model/TrackcreateProperties} The populated <code>TrackcreateProperties</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackcreateProperties();
      if (data.hasOwnProperty('sensor'))
        obj.sensor = ApiClient.convertToType(data['sensor'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('appVersion'))
        obj.appVersion = ApiClient.convertToType(data['appVersion'], 'String');
      if (data.hasOwnProperty('obdDevice'))
        obj.obdDevice = ApiClient.convertToType(data['obdDevice'], 'String');
      if (data.hasOwnProperty('touVersion'))
        obj.touVersion = ApiClient.convertToType(data['touVersion'], 'String');
      if (data.hasOwnProperty('length'))
        obj.length = ApiClient.convertToType(data['length'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = TrackStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * the name of an existing sensor resource
 * @member {String} sensor
 */
TrackcreateProperties.prototype.sensor = undefined;

/**
 * @member {String} name
 */
TrackcreateProperties.prototype.name = undefined;

/**
 * @member {String} description
 */
TrackcreateProperties.prototype.description = undefined;

/**
 * @member {String} appVersion
 */
TrackcreateProperties.prototype.appVersion = undefined;

/**
 * @member {String} obdDevice
 */
TrackcreateProperties.prototype.obdDevice = undefined;

/**
 * @member {String} touVersion
 */
TrackcreateProperties.prototype.touVersion = undefined;

/**
 * @member {Number} length
 */
TrackcreateProperties.prototype.length = undefined;

/**
 * @member {module:model/TrackStatus} status
 */
TrackcreateProperties.prototype.status = undefined;

