/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Geometry} from './Geometry';
import {OptionalUserProperties} from './OptionalUserProperties';
import {Username} from './Username';

/**
 * The UserCreate model module.
 * @module model/UserCreate
 * @version 1.0.0
 */
export class UserCreate extends OptionalUserProperties {
  /**
   * Constructs a new <code>UserCreate</code>.
   * @alias module:model/UserCreate
   * @class
   * @extends module:model/OptionalUserProperties
   * @param name {} 
   * @param mail {} 
   * @param token {} 
   * @param acceptedTerms {} 
   * @param acceptedPrivacy {} 
   */
  constructor(name, mail, token, acceptedTerms, acceptedPrivacy) {
    super();
    this.name = name;
    this.mail = mail;
    this.token = token;
    this.acceptedTerms = acceptedTerms;
    this.acceptedPrivacy = acceptedPrivacy;
  }

  /**
   * Constructs a <code>UserCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCreate} obj Optional instance to populate.
   * @return {module:model/UserCreate} The populated <code>UserCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserCreate();
      OptionalUserProperties.constructFromObject(data, obj);
      if (data.hasOwnProperty('name'))
        obj.name = Username.constructFromObject(data['name']);
      if (data.hasOwnProperty('mail'))
        obj.mail = ApiClient.convertToType(data['mail'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('acceptedTerms'))
        obj.acceptedTerms = ApiClient.convertToType(data['acceptedTerms'], 'Boolean');
      if (data.hasOwnProperty('acceptedPrivacy'))
        obj.acceptedPrivacy = ApiClient.convertToType(data['acceptedPrivacy'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/Username} name
 */
UserCreate.prototype.name = undefined;

/**
 * @member {String} mail
 */
UserCreate.prototype.mail = undefined;

/**
 * @member {String} token
 */
UserCreate.prototype.token = undefined;

/**
 * @member {Boolean} acceptedTerms
 */
UserCreate.prototype.acceptedTerms = undefined;

/**
 * @member {Boolean} acceptedPrivacy
 */
UserCreate.prototype.acceptedPrivacy = undefined;

