/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserStatisticTrackSummaries model module.
 * @module model/UserStatisticTrackSummaries
 * @version 1.0.0
 */
export class UserStatisticTrackSummaries {
  /**
   * Constructs a new <code>UserStatisticTrackSummaries</code>.
   * @alias module:model/UserStatisticTrackSummaries
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserStatisticTrackSummaries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserStatisticTrackSummaries} obj Optional instance to populate.
   * @return {module:model/UserStatisticTrackSummaries} The populated <code>UserStatisticTrackSummaries</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserStatisticTrackSummaries();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('startPosition'))
        obj.startPosition = ApiClient.convertToType(data['startPosition'], Object);
      if (data.hasOwnProperty('endPosition'))
        obj.endPosition = ApiClient.convertToType(data['endPosition'], Object);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserStatisticTrackSummaries.prototype.id = undefined;

/**
 * @member {Object} startPosition
 */
UserStatisticTrackSummaries.prototype.startPosition = undefined;

/**
 * @member {Object} endPosition
 */
UserStatisticTrackSummaries.prototype.endPosition = undefined;

