/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Geometry} from './Geometry';
import {MailAddress} from './MailAddress';
import {OptionalUserProperties} from './OptionalUserProperties';
import {Username} from './Username';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
export class User extends OptionalUserProperties {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   * @extends module:model/OptionalUserProperties
   * @param name {} 
   */
  constructor(name) {
    super();
    this.name = name;
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      OptionalUserProperties.constructFromObject(data, obj);
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('mail'))
        obj.mail = MailAddress.constructFromObject(data['mail']);
      if (data.hasOwnProperty('modified'))
        obj.modified = ApiClient.convertToType(data['modified'], 'Date');
      if (data.hasOwnProperty('name'))
        obj.name = Username.constructFromObject(data['name']);
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
User.prototype.created = undefined;

/**
 * @member {module:model/MailAddress} mail
 */
User.prototype.mail = undefined;

/**
 * @member {Date} modified
 */
User.prototype.modified = undefined;

/**
 * @member {module:model/Username} name
 */
User.prototype.name = undefined;

