"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.TrackStatus = void 0;
var _ApiClient = require("../ApiClient");
/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */

/**
 * Enum class TrackStatus.
 * @enum {String}
 * @readonly
 */
var TrackStatus = {
  /**
   * value: "finished"
   * @const
   */
  finished: "finished",
  /**
   * value: "ongoing"
   * @const
   */
  ongoing: "ongoing",
  /**
   * Returns a <code>TrackStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/TrackStatus} The enum <code>TrackStatus</code> value.
   */
  constructFromObject: function constructFromObject(object) {
    return object;
  }
};
exports.TrackStatus = TrackStatus;