/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnviroCarRestApi);
  }
}(this, function(expect, EnviroCarRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CarpropertiesProperties', function() {
      beforeEach(function() {
        instance = new EnviroCarRestApi.CarpropertiesProperties();
      });

      it('should create an instance of CarpropertiesProperties', function() {
        // TODO: update the code to test CarpropertiesProperties
        expect(instance).to.be.a(EnviroCarRestApi.CarpropertiesProperties);
      });

      it('should have the property manufacturer (base name: "manufacturer")', function() {
        // TODO: update the code to test the property manufacturer
        expect(instance).to.have.property('manufacturer');
        // expect(instance.manufacturer).to.be(expectedValueLiteral);
      });

      it('should have the property model (base name: "model")', function() {
        // TODO: update the code to test the property model
        expect(instance).to.have.property('model');
        // expect(instance.model).to.be(expectedValueLiteral);
      });

      it('should have the property fuelType (base name: "fuelType")', function() {
        // TODO: update the code to test the property fuelType
        expect(instance).to.have.property('fuelType');
        // expect(instance.fuelType).to.be(expectedValueLiteral);
      });

      it('should have the property constructionYear (base name: "constructionYear")', function() {
        // TODO: update the code to test the property constructionYear
        expect(instance).to.have.property('constructionYear');
        // expect(instance.constructionYear).to.be(expectedValueLiteral);
      });

      it('should have the property VIN (base name: "VIN")', function() {
        // TODO: update the code to test the property VIN
        expect(instance).to.have.property('VIN');
        // expect(instance.VIN).to.be(expectedValueLiteral);
      });

    });
  });

}));
