/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnviroCarRestApi);
  }
}(this, function(expect, EnviroCarRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserCreate', function() {
      beforeEach(function() {
        instance = new EnviroCarRestApi.UserCreate();
      });

      it('should create an instance of UserCreate', function() {
        // TODO: update the code to test UserCreate
        expect(instance).to.be.a(EnviroCarRestApi.UserCreate);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property mail (base name: "mail")', function() {
        // TODO: update the code to test the property mail
        expect(instance).to.have.property('mail');
        // expect(instance.mail).to.be(expectedValueLiteral);
      });

      it('should have the property token (base name: "token")', function() {
        // TODO: update the code to test the property token
        expect(instance).to.have.property('token');
        // expect(instance.token).to.be(expectedValueLiteral);
      });

      it('should have the property acceptedTerms (base name: "acceptedTerms")', function() {
        // TODO: update the code to test the property acceptedTerms
        expect(instance).to.have.property('acceptedTerms');
        // expect(instance.acceptedTerms).to.be(expectedValueLiteral);
      });

      it('should have the property acceptedPrivacy (base name: "acceptedPrivacy")', function() {
        // TODO: update the code to test the property acceptedPrivacy
        expect(instance).to.have.property('acceptedPrivacy');
        // expect(instance.acceptedPrivacy).to.be(expectedValueLiteral);
      });

    });
  });

}));
