/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnviroCarRestApi);
  }
}(this, function(expect, EnviroCarRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserStatistic', function() {
      beforeEach(function() {
        instance = new EnviroCarRestApi.UserStatistic();
      });

      it('should create an instance of UserStatistic', function() {
        // TODO: update the code to test UserStatistic
        expect(instance).to.be.a(EnviroCarRestApi.UserStatistic);
      });

      it('should have the property distance (base name: "distance")', function() {
        // TODO: update the code to test the property distance
        expect(instance).to.have.property('distance');
        // expect(instance.distance).to.be(expectedValueLiteral);
      });

      it('should have the property duration (base name: "duration")', function() {
        // TODO: update the code to test the property duration
        expect(instance).to.have.property('duration');
        // expect(instance.duration).to.be(expectedValueLiteral);
      });

      it('should have the property trackCount (base name: "trackCount")', function() {
        // TODO: update the code to test the property trackCount
        expect(instance).to.have.property('trackCount');
        // expect(instance.trackCount).to.be(expectedValueLiteral);
      });

      it('should have the property userstatistic (base name: "userstatistic")', function() {
        // TODO: update the code to test the property userstatistic
        expect(instance).to.have.property('userstatistic');
        // expect(instance.userstatistic).to.be(expectedValueLiteral);
      });

      it('should have the property trackSummaries (base name: "trackSummaries")', function() {
        // TODO: update the code to test the property trackSummaries
        expect(instance).to.have.property('trackSummaries');
        // expect(instance.trackSummaries).to.be(expectedValueLiteral);
      });

    });
  });

}));
