/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnviroCarRestApi);
  }
}(this, function(expect, EnviroCarRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EnviroCarRestApi.SensorsApi();
  });

  describe('(package)', function() {
    describe('SensorsApi', function() {
      describe('createSensor', function() {
        it('should call createSensor successfully', function(done) {
          // TODO: uncomment, update parameter values for createSensor call
          /*

          instance.createSensor(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createSensorForUser', function() {
        it('should call createSensorForUser successfully', function(done) {
          // TODO: uncomment, update parameter values for createSensorForUser call
          /*

          instance.createSensorForUser(body, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMeasurementSensor', function() {
        it('should call getMeasurementSensor successfully', function(done) {
          // TODO: uncomment, update parameter values for getMeasurementSensor call and complete the assertions
          /*

          instance.getMeasurementSensor(measurementId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Sensor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSensorById', function() {
        it('should call getSensorById successfully', function(done) {
          // TODO: uncomment, update parameter values for getSensorById call and complete the assertions
          /*

          instance.getSensorById(sensorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Sensor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSensorStatistics', function() {
        it('should call getSensorStatistics successfully', function(done) {
          // TODO: uncomment, update parameter values for getSensorStatistics call and complete the assertions
          /*

          instance.getSensorStatistics(sensorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Statistics);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSensors', function() {
        it('should call getSensors successfully', function(done) {
          // TODO: uncomment, update parameter values for getSensors call and complete the assertions
          /*
          var opts = {};

          instance.getSensors(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Sensors);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSensorsOfUser', function() {
        it('should call getSensorsOfUser successfully', function(done) {
          // TODO: uncomment, update parameter values for getSensorsOfUser call and complete the assertions
          /*
          var opts = {};

          instance.getSensorsOfUser(userId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Sensors);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackSensor', function() {
        it('should call getTrackSensor successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackSensor call and complete the assertions
          /*

          instance.getTrackSensor(trackId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Sensor);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
