/*
 * enviroCar REST API
 * enviroCar REST API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@envirocar.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EnviroCarRestApi);
  }
}(this, function(expect, EnviroCarRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EnviroCarRestApi.StatisticsApi();
  });

  describe('(package)', function() {
    describe('StatisticsApi', function() {
      describe('getPhenomenonStatistic', function() {
        it('should call getPhenomenonStatistic successfully', function(done) {
          // TODO: uncomment, update parameter values for getPhenomenonStatistic call and complete the assertions
          /*

          instance.getPhenomenonStatistic(phenomenonId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Statistic);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getSensorStatistics', function() {
        it('should call getSensorStatistics successfully', function(done) {
          // TODO: uncomment, update parameter values for getSensorStatistics call and complete the assertions
          /*

          instance.getSensorStatistics(sensorId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Statistics);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getStatisticsOfUser', function() {
        it('should call getStatisticsOfUser successfully', function(done) {
          // TODO: uncomment, update parameter values for getStatisticsOfUser call and complete the assertions
          /*

          instance.getStatisticsOfUser(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Statistics);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTrackStatistics', function() {
        it('should call getTrackStatistics successfully', function(done) {
          // TODO: uncomment, update parameter values for getTrackStatistics call and complete the assertions
          /*

          instance.getTrackStatistics(trackId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.Statistics);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getUserStatistics', function() {
        it('should call getUserStatistics successfully', function(done) {
          // TODO: uncomment, update parameter values for getUserStatistics call and complete the assertions
          /*

          instance.getUserStatistics(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(EnviroCarRestApi.UserStatistic);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
